### PR TITLE
feat: github_routes js => ts

### PR DESCRIPTION
**Pull request by GiovanniCaiazzo01**

### CODE REVIEW

**Comment by bellaabdelouahab** [comment]
here are some tips : 
- for this on you can keep rebasing it till all the routers complete ( see contributing.md) 
- consider converting it to a draft pr till you finish 
- in your future commits try to mention the issue #130 ( generally the issue you re working on ) to make it easy for other to find your pr in case of problem 

@GiovanniCaiazzo01

**Comment by GiovanniCaiazzo01** [comment]
Sure, thanks for the advice, I'm still at my first contributions and I'll try to do things properly @bellaabdelouahab

**Comment by GiovanniCaiazzo01** [comment]
@bellaabdelouahab i think you have done all the other routes right ?, if yes you can review this pr!

**Comment by bellaabdelouahab** [comment]
Okay 👌

**Review by bellaabdelouahab — APPROVED** [review]
Nice.

**Pull request merged**
