### PR TITLE
bugFix/create-admin-user

### PR DESCRIPTION
**Pull request by muttaqin1**
@bellaabdelouahab

### CODE REVIEW

**Comment by bellaabdelouahab** [comment]
You said moving it to a different dir, what did you mean by that?

**Comment by muttaqin1** [comment]
i was asking if we can move this file in the authorization dir.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
sure, amend it to this pr before I merge.

**Comment by muttaqin1** [comment]
hey can you merge this without review? then i will get a yolo😊😁

**Review by bellaabdelouahab — APPROVED** [review]

**Pull request merged**
