### PR TITLE
Creating CONTRIBUTING.md

### LINKED ISSUE #41: docs - CONTRIBUTING.md
creation of a CONTRIBUTING.md 
it works as a guide line for new contributors
here is an example of CONTRIBUTING.md from jhipster project : [Jhipster Registry](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by bellaabdelouahab**
Resolves #41

### CODE REVIEW

**Review by muttaqin1 — CHANGES_REQUESTED** [review]
include:
- [ ]  For file names use lowecase letters with words seperated by underscore.
- [x]  Steps to create github oauth application and add clientId & clientSecret  in .env  #63 
- [ ]  Steps to configure eslint & prettier.
- [ ]  Install exact version of dependencies.

**Comment by bellaabdelouahab** [comment]
how to : Steps to configure eslint & prettier
@muttaqin1

**Comment by bellaabdelouahab** [comment]
and for GitHub auth I will put some comments in the code

**Comment by bellaabdelouahab** [comment]
` Install exact version of dependencies `
what do you mean, the contributor should just run npm install and that's it !

**Comment by muttaqin1** [comment]
> ` Install exact version of dependencies `
> what do you mean, the contributor should just run npm install and that's it !
> 

They might need to install new dependencies. So they should know that they have to install the exact version of the dependency.
For example i need to install lodash.
So i have to do this **npm i --save-exact -D lodash**

@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
if we just remove the ^ from package.json the exact dep will be installed 
@muttaqin1

**Comment by muttaqin1** [comment]
> how to : Steps to configure eslint & prettier
> @muttaqin1 

I will configure pre-commit hooks.
Then i will provide the steps to run husky  you can add them to contributing.md

@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
I'm not sure how.

**Comment by muttaqin1** [comment]
> if we just remove the ^ from package.json the exact dep will be installed 
> @muttaqin1 

In that case you can create a .npmrc.
So you dont have to manually remove those ^.

In that file you can add this line:

```txt
save-exact=true
```

@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
> .npmrc

done

**Comment by muttaqin1** [comment]
> I'm not sure how.

Pre-commit hook is kind of a tool. In that tool we can create a script.
When we run git commit -m "something.."

That tool detects a the event(commit) and runs the script.Basically that tool uses git.


So in that script i can add this line.

```txt
Npm run lint && npm run test
```

**Comment by muttaqin1** [comment]
You can see my project https://github.com/muttaqin1/CipherConvo 

go to .husky directory.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
but as far as i know i pre commit hook is only a local setting for git ?
@muttaqin1

**Comment by muttaqin1** [comment]
> but as far as i know i pre commit hook is only a local setting for git ?
> @muttaqin1 

no, if you push the .husky dir. Then the entire team gets that. and they just have to give permission to the scripts.

```shell
chmod +x pre-commit
chmod +x pre-push
```
Thats how the entire team can use it.

**Comment by bellaabdelouahab** [comment]
ah sure I will do it 👌

**Comment by muttaqin1** [comment]
> ah sure I will do it 👌

okay, i am submitting a pr

**Pull request merged**
