### PR TITLE
Refactor project

### PR DESCRIPTION
**Pull request by ghost**
hello @bellaabdelouahab,
If you face any error.create an issue and assign it to me.

### CODE REVIEW

**Comment by bellaabdelouahab** [comment]
Sure thing 👍

**Comment by bellaabdelouahab** [comment]
Are you more intrested in the backend

**Comment by muttaqin1** [comment]
yes  i'm interested.
i want to know what is your plan about this project. do you want to add new features?
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
The project is at its early stage, we will now focus on addi base structure and then we will move to be more specific in this project
I'm thinking about adding a documentation interface like swager
To manage backend compatibles, if you want to take this taks it would be wonderful, i have other team memebers that will work on this project but for now it's only me and you.

**Comment by bellaabdelouahab** [comment]
Btw the readme file provides the general idea behind this project

**Comment by bellaabdelouahab** [comment]
@muttaqin1

**Comment by muttaqin1** [comment]
Okay. I am taking this task.

**Comment by muttaqin1** [comment]
@bellaabdelouahab 
where should is keep the swagger annotations?
1- In a docs directory where all the annotations will be stored in different files.
2- above the routes.

**Comment by bellaabdelouahab** [comment]
Both looking fine, but i prefer having a docs separate from the other routes

**Comment by muttaqin1** [comment]
I also prefer the same.

**Pull request merged**
