### PR TITLE
Feature/role based access control-2

### PR DESCRIPTION
**Pull request by muttaqin1**
I have made many changes in the role auth feature.It would be better if you review it at once and create some issues if possible.

I am sorry for the change of role property in the user model without asking to you. I believe an array allows you to assign multiple roles to a user. This can be useful if your RBAC system requires users to have overlapping or hierarchical roles. For example, a user might have both "MANAGER" and "SUPERVISOR" roles.
if  you dont like this change i am ready to roleback.
@bellaabdelouahab

### CODE REVIEW

**Comment by bellaabdelouahab** [comment]
I don't mind, the only thing i would suggest is to frequently fetch new updates, because i also have worked on userModel, but it's okay i will merge the files,
An array is the right way to do the authorities restrictions and roles, i was wondering when u will change it cause as you know we can't change the code base every time we want to add new role,

And finally i want your opinion on the frontend part
Should we keep react or change to an other framework, and if so, should we use js or typescript with react.

**Comment by bellaabdelouahab** [comment]
And I'm just on my phone but i see that you kept the authorities as an enum, why do you think it's the right way to go?

**Comment by bellaabdelouahab** [comment]
@muttaqin1

**Comment by muttaqin1** [comment]
'ACTIONS' is a enum.now if we push some actions in the authorities array.It will be the user authorities.And if we push some actions in the restrictions array.If the user have the authorities but cant perform the action because of the restrictions.
here actions act as both authorities and restrictions.

but we can seperate this and Add authorities and restrictions enum.
like Authorities={Delete_user} ,
Restrictions={Cant_Delete_User}
 validate the user using this enums.

both works well.The first approach is very simple.
Give me your opinion about it @bellaabdelouahab

**Comment by muttaqin1** [comment]
Should we keep react or change to an other framework, and if so, should we use js or typescript with react.

I think we can use Typescript with react.And if possible I would like to suggest next.js.
And i love Typescript because it is statically typed.It lets developers add types to their project.we can do function overloading, type level programming.It provides many oop features like abstract classes , protected methods , decorators,  and my most favorite feature dependency injections. Typescript is so cute🥰😊

**Comment by bellaabdelouahab** [comment]
> 'ACTIONS' is a enum.now if we push some actions in the authorities array.It will be the user authorities.And if we push some actions in the restrictions array.If the user have the authorities but cant perform the action because of the restrictions.
> here actions act as both authorities and restrictions.
> 
> but we can seperate this and Add authorities and restrictions enum.
> like Authorities={Delete_user} ,
> Restrictions={Cant_Delete_User}
>  validate the user using this enums.
> 
> both works well.The first approach is very simple.
> Give me your opinion about it @bellaabdelouahab 

You didn't understand me, what I'm saying is if we kept actions as enum it's not good because we might want to add other actions, but we cant change the code every time

**Comment by muttaqin1** [comment]
> > 'ACTIONS' is a enum.now if we push some actions in the authorities array.It will be the user authorities.And if we push some actions in the restrictions array.If the user have the authorities but cant perform the action because of the restrictions.
> > here actions act as both authorities and restrictions.
> > but we can seperate this and Add authorities and restrictions enum.
> > like Authorities={Delete_user} ,
> > Restrictions={Cant_Delete_User}
> > validate the user using this enums.
> > both works well.The first approach is very simple.
> > Give me your opinion about it @bellaabdelouahab
> 
> You didn't understand me, what I'm saying is if we kept actions as enum it's not good because we might want to add other actions, but we cant change the code every time

now i can understand.we can create a action model to save the actions in database.there will be only one Action record.this record will be created when we will host the project. 
also we can keep the actions in a seperate file then we can do CRUD using fs .
which one is great?
@bellaabdelouahab

**Comment by muttaqin1** [comment]
we have to store the role enum in the database too. Then we have to add the functionality to  create ACTIONS and assign them in the ROLE.

**Comment by muttaqin1** [comment]
okay i am taking the task. you can create a issue and assign it to me.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
Okay

**Pull request merged**
