### PR TITLE
Fix security vulnerability in signup controller.

### PR DESCRIPTION
**Pull request by muttaqin1**
We can implement a user role called 'superAdmin' with elevated privileges.
 During the deployment process, we can manually create a user with 'superAdmin' role.
 This superAdmin role will have the ability to create and remove admins.
 I plan to create specific routes in our API that only the superAdmin can access for managing admins.
 It will give us more control over the administrative roles and ensure secure management.
 What do you think?
@bellaabdelouahab

### CODE REVIEW

**Comment by bellaabdelouahab** [comment]
sure, looks great having super admin to manage admins, and obviously we will need it when the project advance, also how about, something like authorities or restrictions, for example one admin can't do certain actions

**Comment by muttaqin1** [comment]
Yeah, sounds great.
I have came up with this solution.Now tell me, what do you think?

//enum
const Authorities = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ADMIN_ACCESS: 'ADMIN_ACCESS',
  FULL_ACCESS: 'FULL_ACCESS',
...................more.
};

//user record
const user = {
  name: 'Muttaqin',
  age: 20,
  gender: 'male',
  // here is the authorities
  roles: {
    SUPER_ADMIN: [Authorities.ADMIN_ACCESS, Authorities.FULL_ACCESS],
    ADMIN: [
      Authorities.CREATE,
      Authorities.READ,
      Authorities.UPDATE,
      Authorities.DELETE,
    ],
    USER: [Authorities.CREATE, Authorities.READ, Authorities.UPDATE],
  },
};

and the restrictTo middleware will take some optional arguments like:
const requiredAuthorities= [Authorities.DELETE]
router.delete('/delete-user',restrictTo('ADMIN", requiredAuthorities, ()=>{
res.json({
msg:user deleted
})
})

**Comment by muttaqin1** [comment]
Now if we want to add more authorities we can just add it to the enum and add it to the roles object.
await user.roles.push(Authorities.NEW_AUTHORITY);
 remove authority from user / admin
await user.roles.admin.splice(user.roles.admin.indexOf(Authorities.DELETE), 1);

**Comment by muttaqin1** [comment]
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
Sounds great, even though i was taking about specific authorities like ban a user, change calendar, accept documents... Because when you talk about a role like create it's too general and you wouldn't find a user that doesn't have right to preform a create action on any collection, did you understand what I mean.
So it would be better if each user has two field one for authorization and one for restriction and then if we have for example a set of special authorisations we then create a role that sums them, just like in oracle architecture.
@muttaqin1

**Comment by muttaqin1** [comment]
Yes i have understood.You have to provide me the authorities and restrictions enum.
create a 'authorization.js' file in the middlewares dir.Put those enum's there And leave the rest of the works for me.😄
make sure to push your eslint and prettier config.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
**well we will leave them empty for now.** 
@muttaqin1

**Comment by muttaqin1** [comment]
okay, i am working on it.
@bellaabdelouahab

**Pull request merged**
