### PR TITLE
Feature/configure logger

### PR DESCRIPTION
**Pull request by muttaqin1**
I have configured winston, morgan logger.There was no config file or directory in your project structure.I haven't created one because i dont want to change your project structure.
so I kept everything in a same file.

If you like this changes I will make another update where all the server logs will be stored in a logs directory.

IMG_20230406_200709

### CODE REVIEW

**Comment by muttaqin1** [comment]
hey @bellaabdelouahab !
I think you don't like the changes. Should i close the pr?

**Comment by bellaabdelouahab** [comment]
No i ve just been busy please contact me on email whenever you have a pr so
i can check it out

**Comment by bellaabdelouahab** [comment]
Also because you took so much time i thought you weren't working on it

**Comment by muttaqin1** [comment]
As you can see.I have submitted this pull request 18 days ago.I was waiting for you to check the request and suggest me if i need to change something.
No problem , i thought you dont like my changes so you dont reply my pr😁
I will contact you through mail next time.
@bellaabdelouahab

**Pull request merged**
