### PR TITLE
Github Oauth integration.

### LINKED ISSUE #58: GitHub integration
This issue aims to implement the initial steps for GitHub integration and retrieve repositories
this will unlock many possibilities in our application.
here are tasks to be done :
- [ ] Implement authentication mechanisms to securely connect to the GitHub API.
- [ ] Store the required access token securely for future API requests
- [ ] Implement a mechanism to retrieve the user's recent repository from their GitHub account, and extract essential information such as repository name, description
- [ ] this is an extra, and yet an important task signup to the application via GitHub.

### PR DESCRIPTION
**Pull request by muttaqin1**
resolved #58

### CODE REVIEW

**Comment by bellaabdelouahab** [comment]
@yassineboujrada  can you review these changes and see if you can implement it on the frontend?

**Comment by muttaqin1** [comment]
> @muttaqin1  you should add some guide on how to get it working.

Create a Oauth application in github -> developers setting -> Oauth application.  Set the callback url = http://localhost:4000/api/v1/auth/github/callback
Then you will get a client id and client secret.
Add those values in the .env file.
Then start the server.
 
For frontend:
Create a index.html file

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <a
      href="https://github.com/login/oauth/authorize?client_id=PUT YOUR CLIENT ID HERE&redirect_url=http://localhost:4000/api/v1/auth/github/callback?path=/&scope=user:email"
      >Login with github</a
    >
  </body>
</html>
```

@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
Thank you, please remind me to add this to contribute.md when we create it.

**Comment by muttaqin1** [comment]
> Thank you, please remind me to add this to contribute.md when we create it. 

You are welcome.I will surely remind you.

**Pull request merged**
