### PR TITLE
Refactor/file names

### LINKED ISSUE #29: The Potential Issues of Using CamelCase in File Names for Cross-Platform Compatibility
Using CamelCase in file names can indeed create problems when working with both Windows and Linux operating systems. While Linux is case-sensitive, meaning it treats "file.txt" and "File.txt" as two different files, Windows is case-insensitive by default, considering them the same file. This can lead to confusion and potential issues when transferring files between the two systems or working on projects collaboratively.

For example, if you have a file named "UserModel.js" in a project and refer to it as "userModel.js" in your code or scripts, it may work fine on Linux but fail to locate the file on Windows. This discrepancy in naming conventions can cause errors and make code less portable.

To ensure cross-platform compatibility and avoid such problems, it is generally recommended to use lowercase filenames with words separated by underscores ("user.js"), ("user_model.js") or hyphens ("my-file.txt") instead of CamelCase when developing projects that need to work on both Windows and Linux. This helps maintain consistency and reduces the chances of issues arising due to case sensitivity differences between the two operating systems.

### PR DESCRIPTION
**Pull request by muttaqin1**
resolved #29 
please check all the files and let me know if i have missed anything.

### CODE REVIEW

**Review by bellaabdelouahab — APPROVED** [review]
looks good, there is only one issue tho, the issue [ #43 ]  needs to be solved as soon as possible

**Comment by muttaqin1** [comment]
> looks good, there is only one issue tho, the issue [ #43 ] needs to be solved as soon as possible

If you provide me eslint & prettier config i can configure a pre-commit hook with husky.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
I'm sorry, but can you explain this to me cause i don't understand the whole thing of eslint config
@muttaqin1

**Comment by muttaqin1** [comment]
> I'm sorry, but can you explain this to me cause i don't understand the whole thing of eslint config @muttaqin1

Sure, but now 3 AM at night and i am feeling very sleepy. Morning i will explain everything.
@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
@muttaqin1

**Comment by muttaqin1** [comment]
**Eslint**: ESLint is a popular JavaScript linting tool that helps developers identify and fix potential problems in their JavaScript code. It analyzes your code based on a set of predefined rules( This rules are eslint Config) and provides warnings or errors for any violations it finds.

**Eslint config**: ESLint config refers to the configuration settings that define how ESLint should behave when analyzing your JavaScript code. ESLint can be highly customizable, allowing developers to specify their own rules or use pre-configured rule sets provided by the ESLint community such as: Eslint  config google, Eslint config Airbnb
@bellaabdelouahab

**Comment by muttaqin1** [comment]
> @muttaqin1 

what a timing 😁😁😁
@bellaabdelouahab

**Comment by muttaqin1** [comment]
> **Eslint**: ESLint is a popular JavaScript linting tool that helps developers identify and fix potential problems in their JavaScript code. It analyzes your code based on a set of predefined rules( This rules are defined in  eslint Config) and provides warnings or errors for any violations it finds.
> 
> **Eslint config**: ESLint config refers to the configuration settings that define how ESLint should behave when analyzing your JavaScript code. ESLint can be highly customizable, allowing developers to specify their own rules or use pre-configured rule sets provided by the ESLint community such as: Eslint  config google, Eslint config Airbnb
> @bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
including converting " to '

**Pull request merged**
